"""add deleted_at to user

Revision ID: 59da44355019
Revises: 0b6d92b1bb05
Create Date: 2025-06-23 22:32:16.694431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59da44355019'
down_revision = '0b6d92b1bb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
